### ISSUE TITLE
Cache: Use dependency injection for custom solutions

### ISSUE THREAD

**Issue by Dwarfex** [openfoodfacts/openfoodfacts-php#12]
Hi, 
as it is mentioned in the code: 
"//TODO : add cache interface ?"  https://github.com/openfoodfacts/openfoodfacts-php/blob/deeef6cb617b53e63fe115976afdf0db039bbfa5/src/Api.php#L116

I would suggest adding either an PSR-6 "Caching Interface" or PSR-16: "Common Interface for Caching Libraries". 
I personally would prefer PSR-16 and i'm already working on a PR to solve this issue.

**Comment by Benoit382** [comment]
It was PSR-6.

**Comment by rampmaster** [comment]
done
