### ISSUE TITLE
Implementation of v2 Search

### ISSUE THREAD

**Issue by Dwarfex** [openfoodfacts/openfoodfacts-php#24]
### What

- As a new version of the Search API is developed, this Library should also implement the usage of it.

See: https://wiki.openfoodfacts.org/Open_Food_Facts_Search_API_Version_2

> The existing Open Food Facts search API is outdated and hacky (it was built on top of the OFF web site search form and is unnecessarily convoluted) and does not support some of the requirements for the Project:Personalized_Search (in particular being able to retrieve a given set of products using their barcodes).
> We are thus creating a new Open Food Facts Search API Version 2 that will be simpler but also more powerful.

### Part of
- #39

**Comment by teolemon** [comment]
- We now have https://search.openfoodfacts.org/docs, based on OpenAPI and Elastic Search @Dwarfex

**Comment by Benoit382** [comment]
@teolemon Where the openapi.json file is generated ? 
I would like to fix it

**Comment by teolemon** [comment]
Great 👍 It's located at https://github.com/openfoodfacts/search-a-licious

**Comment by Benoit382** [comment]
I work on autocomplete feature, could you provide me some query example ? (`q` and  `taxonomy_names`)

**Comment by Benoit382** [comment]
The pull request is ready https://github.com/openfoodfacts/openfoodfacts-php/pull/62
