### ISSUE TITLE
Fix failed tests 

### ISSUE THREAD

**Issue by Dwarfex** [openfoodfacts/openfoodfacts-php#27]
It seems as if the API response has changed. 

As seen in the test executions an index in collections ('page' ) seems to be missing (https://travis-ci.org/github/openfoodfacts/openfoodfacts-php/jobs/735694395)

https://github.com/openfoodfacts/openfoodfacts-php/blob/49808014d335af6dbac3162effc85e4f460d9e39/src/Collection.php#L50

**Comment by sebrave** [comment]
https://github.com/openfoodfacts/openfoodfacts-php/pull/28
