### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by Dwarfex** [openfoodfacts/openfoodfacts-php#33]
We should add a new relase with included PHP 8.0 support and drop 7.2

**Comment by Benoit382** [comment]
I add the support of PHP8 : https://github.com/openfoodfacts/openfoodfacts-php/pull/35

**Comment by Dwarfex** [comment]
Nice - i'll have a look ... (sry really busy at the moment)

**Comment by Dwarfex** [comment]
done with PR #35
