### ISSUE TITLE
Add support for psr/log 2.0 or 3.0

### ISSUE THREAD

**Issue by khalyomede** [openfoodfacts/openfoodfacts-php#45]
### Problem

I want to add support for Laravel 10 within open food fact laravel package, and Laravel 10 now relies on psr/log:^2.0|^3.0, but since it relies on this package, and this package only supports psr/log:^1.0, it cannot be updated while this package is not updated as well.

### Proposed solution

Upgrade psr/log to ^2.0 or ^3.0 (or both).

### Part of

- https://github.com/openfoodfacts/openfoodfacts-laravel/issues/39

**Comment by Benoit382** [comment]
Could be closed, psr/log has been updated

**Comment by teolemon** [comment]
thanks @Benoit382 , in those cases, feel free to close
