### ISSUE TITLE
Add support for automatic publication of the package

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-php#63]
### What
- Add support for automatic publication of the package
- https://packagist.org/packages/openfoodfacts/openfoodfacts-php

**Comment by Dwarfex** [comment]
A Release (https://github.com/openfoodfacts/openfoodfacts-php/releases) results in automatic publication. 
So I'd say - this task is done.

**Comment by teolemon** [comment]
thanks @Dwarfex 👍
